name: deploy
on:
  push:
    tags:
    - "v*.*.*"

jobs:
  release-containers:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get the version
      if: startsWith(github.ref, 'refs/tags/')
      id: get_tag
      shell: bash
      run: echo ::set-output name=GIT_TAG::${GITHUB_REF/refs\/tags\//}
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      env:
        VERSION: ${{ steps.get_tag.outputs.GIT_TAG }}
        BUILDFLAGS: -ldflags=" -X github.com/replicatedhq/local-volume-provider/pkg/version.version=${{ steps.get_tag.outputs.GIT_TAG }} "
        DOCKER_CONFIG: ./.docker
      run: |
        make container
